import json
from kafka import KafkaProducer

producer = KafkaProducer(
    bootstrap_servers="localhost:9092",
    value_serializer=lambda value: json.dumps(value).encode("utf-8")
)

def send_event(event):
    """
    Publish an event to the Kafka 'orders' topic.

    Args:
        event (dict): Business event generated by event_generator.py

    Returns:
        kafka.producer.future.FutureRecordMetadata:
            A future representing the asynchronous send operation.
    """
    future = producer.send(
        "orders",
        value=event
    )

    producer.flush()

    return future