from __future__ import annotations

import json
import os
from typing import Any

from dotenv import load_dotenv
from kafka import KafkaProducer
from kafka.producer.future import FutureRecordMetadata


load_dotenv()


def _require_environment_variable(name: str) -> str:
    """Return a required environment variable or fail clearly."""

    value = os.getenv(name)

    if not value:
        raise RuntimeError(
            f"Required environment variable '{name}' is missing."
        )

    return value


def _create_local_producer() -> tuple[KafkaProducer, str]:
    """
    Create a producer for the local Docker Kafka broker.
    """

    bootstrap_servers = os.getenv(
        "LOCAL_KAFKA_BOOTSTRAP_SERVERS",
        "kafka:9092",
    )

    topic = os.getenv(
        "LOCAL_KAFKA_TOPIC",
        "orders",
    )

    producer = KafkaProducer(
        bootstrap_servers=bootstrap_servers,
        value_serializer=lambda value: json.dumps(value).encode(
            "utf-8"
        ),
        key_serializer=lambda key: str(key).encode("utf-8"),
        acks="all",
        retries=5,
    )

    return producer, topic


def _create_event_hubs_producer() -> tuple[KafkaProducer, str]:
    """
    Create a Kafka producer connected to Azure Event Hubs.
    """

    namespace = _require_environment_variable(
        "EVENTHUB_NAMESPACE"
    )

    connection_string = _require_environment_variable(
        "EVENTHUB_PRODUCER_CONNECTION_STRING"
    )

    topic = os.getenv(
        "EVENTHUB_TOPIC",
        "orders",
    )

    bootstrap_servers = (
        f"{namespace}.servicebus.windows.net:9093"
    )

    producer = KafkaProducer(
        bootstrap_servers=bootstrap_servers,

        # Azure Event Hubs Kafka authentication
        security_protocol="SASL_SSL",
        sasl_mechanism="PLAIN",
        sasl_plain_username="$ConnectionString",
        sasl_plain_password=connection_string,

        value_serializer=lambda value: json.dumps(value).encode(
            "utf-8"
        ),
        key_serializer=lambda key: str(key).encode("utf-8"),

        acks="all",
        retries=5,
        request_timeout_ms=30_000,
    )

    return producer, topic


def _create_producer() -> tuple[KafkaProducer, str, str]:
    """
    Create the producer selected through KAFKA_MODE.

    Supported modes:
        local
        eventhubs
    """

    mode = os.getenv(
        "KAFKA_MODE",
        "local",
    ).strip().lower()

    if mode == "local":
        producer, topic = _create_local_producer()

    elif mode == "eventhubs":
        producer, topic = _create_event_hubs_producer()

    else:
        raise ValueError(
            "Unsupported KAFKA_MODE. "
            "Expected 'local' or 'eventhubs', "
            f"but received '{mode}'."
        )

    return producer, topic, mode


producer, topic, kafka_mode = _create_producer()


def send_event(
    event: dict[str, Any],
) -> FutureRecordMetadata:
    """
    Publish a ShopSphere order event.

    The customer ID is used as the Kafka key so events for the
    same customer are consistently routed to the same partition.
    """

    customer_id = event["payload"]["customer_id"]

    future = producer.send(
        topic,
        value=event,
        key=customer_id,
    )

    metadata = future.get(timeout=30)

    print(
        f"[Producer:{kafka_mode}] "
        f"Customer={customer_id} | "
        f"Topic={metadata.topic} | "
        f"Partition={metadata.partition} | "
        f"Offset={metadata.offset}"
    )

    return metadata



# import json
# from kafka import KafkaProducer

# producer = KafkaProducer(
#     bootstrap_servers="kafka:9092",
#     value_serializer=lambda value: json.dumps(value).encode("utf-8"),
#     key_serializer=lambda key: str(key).encode("utf-8"),
#     acks = "all"
# )



# def send_event(event):
#     """
#     Publish an event to the Kafka 'orders' topic.

#     Args:
#         event (dict): Business event generated by event_generator.py

#     Returns:
#         kafka.producer.future.FutureRecordMetadata:
#             A future representing the asynchronous send operation.
#     """

#     customer_id = event["payload"]["customer_id"]


#     future = producer.send(
#         "orders",
#         value=event,
#         key=customer_id
#     )

#     producer.flush()

#     metadata = future.get(timeout=10)

#     print(
#         f"[Producer]"
#         f"Customer = {customer_id} | "
#         f"Partition = {metadata.partition} | "
#         f"Offset = {metadata.offset} | "
#     )

#     return future